services:

  chatbot_fatec_whirlpool:
    # image: 'tarsislimafatec/chatbot_fatec_whirlpool'
    build: './src/chatbot_fatec_whirlpool'
    environment:
      - GEMINI_API_KEY=
    ports:
      - '5000:5000'
