# -*- coding: utf-8 -*-
"""chat4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13iRZaqQSz5l1jZwl5ToXq5DodHpLuxfh
"""

from google import genai

client = genai.Client(api_key="sua api key")

import spacy
from sentence_transformers import SentenceTransformer, util
from transformers import pipeline
!python -m spacy download pt_core_news_lg
nlp = spacy.load("pt_core_news_lg")
import gradio as gr
import re

model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

faq = {

    "oi" : "Oi! Sou seu assistente virtual. Em que posso ajudar?",


    "ola" : "Olá! Sou seu assistente virtual. Em que posso ajudar?",



    "preciso de ajuda" : "Olá! Sou seu assistente virtual. Em que posso ajudar?",



    "Quero falar com o suporte humano": "O numero para o nosso suporte é: 19 xxxx-xxx",



    "Preciso falar com o seu suporte" : "O numero para o nosso suporte é: 19 xxxx-xxx",



    "minha máquina de lavar não está ligando": "Verifique se o cabo de energia está bem conectado e se há energia na tomada. Se o problema persistir, entre em contato com a assistência técnica.",



    "a máquina de lavar está fazendo barulho": "Certifique-se de que não há moedas, botões ou objetos soltos no tambor. Barulhos fortes também podem indicar desequilíbrio na carga.",



    "como limpar o filtro da máquina de lavar": "Desligue a máquina da tomada, abra a tampa inferior e retire o filtro girando-o no sentido anti-horário. Lave com água corrente e recoloque.",



    "a roupa sai muito molhada da máquina": "Verifique se o ciclo de centrifugação está selecionado corretamente. Cargas muito grandes ou mal distribuídas podem afetar o desempenho.",



    "como faço para usar o modo econômico da máquina": "Selecione o ciclo ‘Econômico’ ou ‘Rápido’ no painel e use a quantidade de sabão indicada no manual. Isso economiza água e energia.",



    "a máquina está com mau cheiro": "Recomenda-se fazer uma lavagem com o tambor vazio, utilizando vinagre branco ou produtos específicos para limpeza de máquinas.",



    "meu fogão não está acendendo": "Verifique se o gás está aberto e se o acendimento automático está funcionando. Caso use fósforo, veja se o queimador não está entupido.",


    "como limpar o forno do fogão": "Use um pano úmido com detergente neutro. Evite produtos abrasivos. Para sujeiras pesadas, use vinagre morno e bicarbonato.",



    "meu forno não aquece direito": "Verifique se o seletor de temperatura está funcionando e se o acendimento está completo. Caso o problema continue, pode ser falha no termostato.",



    "como saber o tamanho do botijão ideal": "Verifique o manual do seu modelo. A maioria dos fogões domésticos utiliza botijões de 13 kg com válvula padrão.",



    "quanto tempo dura o acendimento automático": "Depende do modelo, mas em média o acendimento deve ocorrer em até 3 segundos após pressionar o botão."



}


def limpar_texto(texto):
    texto = texto.lower()

    texto_sem_pontuacao = re.sub(r'[^\w\s]', '', texto)

    texto_final = ' '.join(texto_sem_pontuacao.split())

    return texto_final

def preprocessar(texto):

    doc = nlp(texto.lower())

    tokens_validos = []



    for token in doc:

        if not token.is_stop and token.is_alpha:

            tokens_validos.append(token.lemma_)



    return " ".join(tokens_validos)


faq_list = list(faq.keys())

faq_processadas = []

for pergunta in faq_list:
    texto_processado = preprocessar(pergunta)
    pergunta_sem_pontuacao = limpar_texto(texto_processado)

    faq_processadas.append(pergunta_sem_pontuacao)

faq_embeddings = model.encode(faq_processadas, convert_to_tensor=True)


def responder_mensagem(mensagem, historico=None):








    sem_pontuacao = limpar_texto(mensagem)
    usuario_limpo = preprocessar(sem_pontuacao).lower()
    usuario_embedding = model.encode(usuario_limpo, convert_to_tensor=True)

    similaridades = util.cos_sim(usuario_embedding, faq_embeddings)[0]
    indice = similaridades.argmax().item()
    melhor_pergunta = faq_list[indice]
    melhor_resposta = faq[melhor_pergunta]
    pontuacao = similaridades[indice].item()

    # Escolher resposta
    if pontuacao <= 0.64:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=f"Você é um chatbot para a whirlpool de Rio Claro e a pergunta do cliente não se encontra dentro da FAQ, porém auxilie ele a fazer perguntas sobre a FAQ no caso: {faq_list}. empresa que no caso é a whirlpool de rio claro que produz maquina de lavar e fogao e também não precisa dar todas opções de faq ao usuario, caso a mensagem do usuario seja saudações, agradeciemntos ou despedidas apenas responda de forma breve e cordialmente a pergunta dele foi: {mensagem}"
        )
        resposta = f"{response.text}"
    else:
        resposta = melhor_resposta

    return resposta
import gradio as gr

gr.ChatInterface(
    fn=responder_mensagem,
    title="ChatBot Whirlpool 🧠",
    description="Chat de exemplo com Gradio atualizado."
).launch(share=True)

